name: presto-stats-build

on:
  push:
    branches:
      - main
      - ci-cd

env:
  CI: false
  REACT_APP_SERVER_HOST: https://gxvz0v65xd.execute-api.us-east-1.amazonaws.com

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: go mod download

      - name: Build server
        # run: GOOS=linux GOARCH=amd64 go build -o server server.go
        run: CGO_ENABLED=0 go build -o server server.go

      - name: Zip build
        run: zip -r server.zip server

      - name: Update Lambda function code
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.2
        with:
          zip-file: server.zip
          lambda-name: presto-stats-server
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd dashboard-ui && yarn install

      - name: Build frontend
        run: cd dashboard-ui && NODE_OPTIONS=--openssl-legacy-provider yarn build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: alluxio.presto-stats.ui
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: dashboard-ui/build